export default {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_USERS_UPDATE: 'AUTH_USERS_UPDATE',
  AUTH_RESET: 'AUTH_RESET',
  AUTH_USER_SET: 'AUTH_USER_SET',
  AUTH_LOADING: 'AUTH_LOADING',
  AUTH_ERROR: 'AUTH_ERROR',
};
