export default {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_DETAILS_UPDATE: 'AUTH_DETAILS_UPDATE',
  AUTH_RESET: 'AUTH_RESET',
  AUTH_DETAILS_SET: 'AUTH_DETAILS_SET',
  AUTH_LOADING: 'AUTH_LOADING',
  AUTH_ERROR: 'AUTH_ERROR',
};
